//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAT_207.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANAL_DOC_C190
    {
        public long ID { get; set; }
        public string REG { get; set; }
        public string CST_ICMS { get; set; }
        public string CFOP { get; set; }
        public Nullable<decimal> ALIQ_ICMS { get; set; }
        public Nullable<decimal> VL_OPR { get; set; }
        public Nullable<decimal> VL_BC_ICMS { get; set; }
        public Nullable<decimal> VL_ICMS { get; set; }
        public Nullable<decimal> VL_BC_ICMS_ST { get; set; }
        public Nullable<decimal> VL_ICMS_ST { get; set; }
        public Nullable<decimal> VL_RED_BC { get; set; }
        public Nullable<decimal> VL_IPI { get; set; }
        public string COD_OBS { get; set; }
        public string PERIODO { get; set; }
        public string NUM_DOC { get; set; }
    }
}
