//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAT_207.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARQUIVOS_GERADOS
    {
        public long ID_ARQUIVO { get; set; }
        public string ARQUIVO { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> PMC { get; set; }
        public string PERIODO_ARQUIVO { get; set; }
        public string PERIODO_GERACAO { get; set; }
    }
}
