//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAT_207.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVOLUCAO_C113
    {
        public long ID { get; set; }
        public string REG { get; set; }
        public string IND_OPER { get; set; }
        public string IND_EMIT { get; set; }
        public string COD_PART { get; set; }
        public string COD_MOD { get; set; }
        public string SER { get; set; }
        public string SUB { get; set; }
        public string NUM_DOC { get; set; }
        public string DT_DOC { get; set; }
        public string PERIODO { get; set; }
    }
}
