//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAT_207.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOC_FISCAL_C100
    {
        public long ID { get; set; }
        public string REG { get; set; }
        public string IND_OPER { get; set; }
        public string IND_EMIT { get; set; }
        public string COD_PART { get; set; }
        public string COD_MOD { get; set; }
        public string COD_SIT { get; set; }
        public string SER { get; set; }
        public string NUM_DOC { get; set; }
        public string CHV_NFE { get; set; }
        public string DT_DOC { get; set; }
        public string DT_E_S { get; set; }
        public Nullable<decimal> VL_DOC { get; set; }
        public string IND_PGTO { get; set; }
        public Nullable<decimal> VL_DESC { get; set; }
        public Nullable<decimal> VL_ABAT_NT { get; set; }
        public Nullable<decimal> VL_MERC { get; set; }
        public string IND_FRT { get; set; }
        public Nullable<decimal> VL_FRT { get; set; }
        public Nullable<decimal> VL_SEG { get; set; }
        public Nullable<decimal> VL_OUT_DA { get; set; }
        public Nullable<decimal> VL_BC_ICMS { get; set; }
        public Nullable<decimal> VL_ICMS { get; set; }
        public Nullable<decimal> VL_BC_ICMS_ST { get; set; }
        public Nullable<decimal> VL_ICMS_ST { get; set; }
        public Nullable<decimal> VL_IPI { get; set; }
        public Nullable<decimal> VL_PIS { get; set; }
        public Nullable<decimal> VL_COFINS { get; set; }
        public Nullable<decimal> VL_PIS_ST { get; set; }
        public Nullable<decimal> VL_COFINS_ST { get; set; }
        public string PERIODO { get; set; }
    }
}
