//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAT_207.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENQ_OP
    {
        public long ID_ENQ_OP { get; set; }
        public Nullable<int> COD_ENQUADRAMENTO { get; set; }
        public string NUM_DOC { get; set; }
        public string SER { get; set; }
        public string PERIODO { get; set; }
        public Nullable<bool> COMPROV_OP { get; set; }
    }
}
