//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAT_207.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENQUADRAMENTO_5D
    {
        public int COD_ENQUADRAMENTO { get; set; }
        public Nullable<int> COD_HIP_GER { get; set; }
        public string ANEXO { get; set; }
        public string ARTIGO { get; set; }
        public string INCISO { get; set; }
        public string ALINEA { get; set; }
        public string PARAGRAFO { get; set; }
        public string ITEM { get; set; }
        public string LETRA { get; set; }
        public string OBS { get; set; }
        public string PERIODO { get; set; }
    }
}
