//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAT_207.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDADE_COMPL_0005
    {
        public long ID { get; set; }
        public string REG { get; set; }
        public string FANTASIA { get; set; }
        public string CEP { get; set; }
        public string END { get; set; }
        public string NUM { get; set; }
        public string COMPL { get; set; }
        public string BAIRRO { get; set; }
        public string FONE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string PERIODO { get; set; }
    }
}
