//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAT_207.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIA
    {
        public long ID_GIA { get; set; }
        public Nullable<decimal> VALOR_CONTABIL { get; set; }
        public Nullable<decimal> BASE_CALCULO { get; set; }
        public Nullable<decimal> IMPOSTO { get; set; }
        public string CFOP { get; set; }
        public string PERIODO_GIA { get; set; }
        public string PERIODO_ARQUIVO { get; set; }
    }
}
