//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAT_207.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_0200
    {
        public long ID { get; set; }
        public string REG { get; set; }
        public string COD_ITEM { get; set; }
        public string DESCR_ITEM { get; set; }
        public string COD_BARRA { get; set; }
        public string COD_ANT_ITEM { get; set; }
        public string UNID_INV { get; set; }
        public string TIPO_ITEM { get; set; }
        public string COD_NCM { get; set; }
        public string EX_IPI { get; set; }
        public string COD_GEN { get; set; }
        public string COD_LST { get; set; }
        public Nullable<decimal> ALIQ_ICMS { get; set; }
        public string PERIODO { get; set; }
    }
}
