//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAT_207.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITENS_DOC_C170
    {
        public long ID { get; set; }
        public string REG { get; set; }
        public string NUM_ITEM { get; set; }
        public string COD_ITEM { get; set; }
        public string DESCR_COMPL { get; set; }
        public Nullable<decimal> QTD { get; set; }
        public string UNID { get; set; }
        public Nullable<decimal> VL_ITEM { get; set; }
        public Nullable<decimal> VL_DESC { get; set; }
        public string IND_MOV { get; set; }
        public string CST_ICMS { get; set; }
        public string CFOP { get; set; }
        public string COD_NAT { get; set; }
        public Nullable<decimal> VL_BC_ICMS { get; set; }
        public Nullable<decimal> ALIQ_ICMS { get; set; }
        public Nullable<decimal> VL_ICMS { get; set; }
        public Nullable<decimal> VL_BC_ICMS_ST { get; set; }
        public Nullable<decimal> ALIQ_ST { get; set; }
        public Nullable<decimal> VL_ICMS_ST { get; set; }
        public string IND_APUR { get; set; }
        public string CST_IPI { get; set; }
        public string COD_ENQ { get; set; }
        public Nullable<decimal> VL_BC_IPI { get; set; }
        public Nullable<decimal> ALIQ_IPI { get; set; }
        public Nullable<decimal> VL_IPI { get; set; }
        public string CST_PIS { get; set; }
        public Nullable<decimal> VL_BC_PIS { get; set; }
        public Nullable<decimal> ALIQ_PIS_PCT { get; set; }
        public Nullable<decimal> QUANT_BC_PIS { get; set; }
        public Nullable<decimal> ALIQ_PIS { get; set; }
        public Nullable<decimal> VL_PIS { get; set; }
        public string CST_COFINS { get; set; }
        public Nullable<decimal> VL_BC_COFINS { get; set; }
        public Nullable<decimal> ALIQ_COFINS_PCT { get; set; }
        public Nullable<decimal> QUANT_BC_COFINS { get; set; }
        public Nullable<decimal> ALIQ_COFINS { get; set; }
        public Nullable<decimal> VL_COFINS { get; set; }
        public string COD_CTA { get; set; }
        public string PERIODO { get; set; }
        public string NUM_DOC { get; set; }
    }
}
