//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAT_207.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IVA
    {
        public int ID_IVA { get; set; }
        public string CNAE { get; set; }
        public Nullable<decimal> IVA_MEDIANA { get; set; }
    }
}
