//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAT_207.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPANTE_0150
    {
        public long ID { get; set; }
        public string REG { get; set; }
        public string COD_PART { get; set; }
        public string NOME { get; set; }
        public string COD_PAIS { get; set; }
        public string CNPJ { get; set; }
        public string CPF { get; set; }
        public string IE { get; set; }
        public string COD_MUN { get; set; }
        public string SUFRAMA { get; set; }
        public string END { get; set; }
        public string NUM { get; set; }
        public string COMPL { get; set; }
        public string BAIRRO { get; set; }
        public string PERIODO { get; set; }
        public string UF { get; set; }
        public string CEP { get; set; }
    }
}
