//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAT_207.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_150_C100_C190_ENQ_OP
    {
        public long ID { get; set; }
        public string NUM_DOC { get; set; }
        public string COD_PART { get; set; }
        public string SER { get; set; }
        public string CHV_NFE { get; set; }
        public string DT_DOC { get; set; }
        public string DT_E_S { get; set; }
        public Nullable<decimal> VL_DOC { get; set; }
        public Nullable<decimal> VL_DESC { get; set; }
        public Nullable<decimal> VL_MERC { get; set; }
        public string PERIODO { get; set; }
        public string NOME { get; set; }
        public string CNPJ { get; set; }
        public string COD_MOD { get; set; }
        public Nullable<decimal> VL_BC_ICMS { get; set; }
        public Nullable<decimal> VL_ICMS { get; set; }
        public string CPF { get; set; }
        public Nullable<bool> COMPROV_OP { get; set; }
        public Nullable<int> COD_ENQUADRAMENTO { get; set; }
        public string CFOP { get; set; }
        public Nullable<decimal> VL_OPR { get; set; }
        public Nullable<decimal> ALIQ_ICMS { get; set; }
        public string UF { get; set; }
        public Nullable<int> COD_HIP_GER { get; set; }
    }
}
