//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAT_207.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Sintegra
    {
        public System.Guid ID { get; set; }
        public string NUM_DOC { get; set; }
        public string COD_PART { get; set; }
        public string SER { get; set; }
        public string DT_DOC { get; set; }
        public decimal VL_DOC { get; set; }
        public decimal VL_DESC { get; set; }
        public decimal VL_MERC { get; set; }
        public string PERIODO { get; set; }
        public Nullable<int> COD_HIP_GER { get; set; }
        public string NOME { get; set; }
        public string CNPJ { get; set; }
        public decimal VL_BC_ICMS { get; set; }
        public decimal VL_ICMS { get; set; }
        public string CPF { get; set; }
        public string CFOP { get; set; }
        public decimal ALIQ_ICMS { get; set; }
        public string UF { get; set; }
        public string SituacaoNF { get; set; }
        public string Emitente { get; set; }
    }
}
